name: Deploy WASM (Live)

on:
  push:
    branches: [master]

jobs:
  deploy-to-ftp:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Update Base URL
        shell: bash
        run: !
         sed -i -e 's*href="/"*href="/@/"*g' ./BlazorWebAssembly/wwwroot/index.html

      - name: Publish .NET Core Project
        run: dotnet publish BlazorWebAssembly/BlazorWebAssembly.csproj -c Release -o bin --nologo

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ SECRETS.FTP_SERVER }}
          username: ${{ SECRETS.FTP_USERNAME }}
          password: ${{ SECRETS.FTP_PASSWORD }}
          local-dir: bin/wwwroot/
          server-dir: './@/' # DO NOT CHANGE THIS, THIS GOES TO A LIVE WEBSITE